workflows:
  simulator-workflow:
    name: Build for simulator

    environment:
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_VERSION: 3.24.5

    scripts:
      - name: Install FVM and Flutter
        script: |
          dart pub global activate fvm
          fvm install
          fvm install $FLUTTER_VERSION
          fvm use $FLUTTER_VERSION

      - name: Check Flutter version
        script: fvm flutter --version

      - name: Install Flutter packages
        script: fvm flutter pub get

      - name: Generate localization files
        script: fvm flutter gen-l10n

      - name: Clean previous build
        script: fvm flutter clean

      - name: Resolve CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build with Generic Destination
        script: |
          xcodebuild build \
            -project "ios/Runner.xcodeproj" \
            -scheme "Runner" \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    artifacts:
      - /Users/builder/Library/Developer/Xcode/DerivedData/**/*.app

    cache:
      cache_paths:
        - ~/.pub-cache
        - .dart_tool/
        - build/
        - ios/Pods
