workflows:
  simulator-workflow:
    name: Build for simulator
    environment:
      xcode: 15.3
      flutter: 3.24.5
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Generate localization files
        script: |
          flutter gen-l10n

      - name: Clean & generate iOS build files
        script: |
          flutter clean
          flutter build ios --debug --no-codesign --simulator

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Build with xcodebuild (simulator)
        script: |
          xcodebuild build \
            -project ios/Runner.xcodeproj \
            -scheme Runner \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator'

    artifacts:
      - /Users/builder/Library/Developer/Xcode/DerivedData/**/*.app
