workflows:
  simulator-workflow:
    name: Build for simulator

    environment:
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_VERSION: 3.24.5

    scripts:
      - name: Install FVM and Flutter
        script: |
          dart pub global activate fvm
          fvm install
          fvm install $FLUTTER_VERSION
          fvm use $FLUTTER_VERSION

      - name: Check Flutter version
        script: fvm flutter --version

      - name: Clean previous build
        script: fvm flutter clean

      - name: Install Flutter packages
        script: fvm flutter pub get

      - name: Generate localization files
        script: fvm flutter gen-l10n

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS app for simulator
        script: fvm flutter build ios --debug --simulator --no-codesign

    artifacts:
      - build/ios/iphonesimulator/*.app