workflows:
  simulator-workflow:
    name: Build for simulator
    environment:
      xcode: 15.3
      flutter: 3.24.5  # or your specific version
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Generate iOS configs
        script: |
          flutter build ios --debug --no-codesign

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build with Generic Destination
        script: |
          xcodebuild build \
            -project "ios/Runner.xcodeproj" \
            -scheme "Runner" \
            -sdk iphonesimulator \
            -configuration Debug

    artifacts:
      - /Users/builder/Library/Developer/Xcode/DerivedData/**/*.app
